source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Resolver_Example', :exclusive => true do
  pod "Resolver", :path => "../"
end

target 'Resolver_Tests', :exclusive => true do
  pod "Resolver", :path => "../"

  
end
